モデル作成
aishimakouki/pakulog pull request #1
Opened 2018-06-22 10:48 UTC by aishimakouki

モデル作成とgem追加

2018-06-22 10:52 UTC, aishimakouki commented
@kazu-taka 
確認お願いします。

2018-06-22 11:07 UTC, kazu-taka requested changes

2018-06-22 11:07 UTC, kazu-taka commented on db/migrate/20180621070838_create_shops.rb
> +      t.string :name
@aishimakouki 
`null: false`と`default: ""`が抜けています。
他のカラムも確認お願いします。

2018-06-25 11:11 UTC, kazu-taka requested changes

2018-06-25 11:11 UTC, kazu-taka commented on db/migrate/20180621070838_create_shops.rb
> +      t.integer :budget_min, null: false
@aishimakouki 
budget_min〜review_avgに、`default: 0`が必要になります。

2018-06-25 11:11 UTC, kazu-taka commented on db/migrate/20180621072205_devise_create_users.rb
> +      t.string :nick_name
@aishimakouki 
nick_nameにも`null: false`と`default: ""`が必要になります。

2018-06-25 11:11 UTC, kazu-taka commented on app/models/shop.rb
> +  validates : budget_min, presence: true
@aishimakouki 
下限と上限は逆転してはいけないので下記の記述を追加して下さい。
うまく動かない時は連絡下さい:bow:
```
validates : budget_min, presence: true, compare: {  compare_to: 'budget_max', type: :less_than }
```

`:less_than` - 指定された値よりも小さくなければならないことを指定します。

2018-06-25 11:11 UTC, kazu-taka commented on app/models/user.rb
> +  mount_uploader :image, ImageUploader
@aishimakouki 
`nick_name`にも`presence: true`のバリデーションをかけて下さい。

2018-06-25 11:11 UTC, kazu-taka commented on app/models/review.rb
> +class Review < ApplicationRecord
@aishimakouki 
レビューも`title`、`description`、`evaluation`に必須のバリデーションを追加して下さい

2018-06-25 11:11 UTC, kazu-taka commented on app/models/genre.rb
> +class Genre < ApplicationRecord
@aishimakouki 
`name`に必須のバリデーションを追加して下さい。

2018-06-25 11:11 UTC, kazu-taka commented on app/models/area.rb
> +class Area < ApplicationRecord
@aishimakouki 
`name`に必須のバリデーションを追加して下さい。

2018-06-26 12:11 UTC, kazu-taka commented
@aishimakouki 
前回の指摘漏れがありました。
バリデーションに関してですが、コロンの後ろにスペースが入っているとエラーに
なるので、修正お願いします。
```
誤 validates : name, presence: true
正 validates :name, presence: true
```

2018-06-26 12:13 UTC, kazu-taka commented on app/models/shop.rb
> +  validates : budget_min, presence: true, compare: {  compare_to: 'budget_max', type: :less_than }
@aishimakouki 
ここのbuget_minのバリデーションを追加した場合、上に記述している
`validates : budget_min, presence: true`は不要になります。

2018-06-26 12:13 UTC, kazu-taka commented on app/models/user.rb
> +  mount_uploader :image, ImageUploader
@aishimakouki 
nick_nameのバリデーションが抜けているので追加して下さい！

2018-06-26 12:15 UTC, kazu-taka requested changes

2018-06-26 12:15 UTC, kazu-taka commented on config/routes.rb
> +     get 'top'
@aishimakouki 
細かくて申し訳ないですが、`get top`を半角スペース1文字インデントお願いします！

2018-06-27 08:35 UTC, kazu-taka approved these changes

2018-06-27 08:36 UTC, kazu-taka commented
マージします！！

2018-06-27 08:36 UTC, merged